# Generated by Django 4.1 on 2024-09-25 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorites', '0003_remove_favorite_author_remove_userprofile_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('place_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='description',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='title',
        ),
        migrations.AlterField(
            model_name='favorite',
            name='place_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='favorite',
            table=None,
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
