# Generated by Django 4.1 on 2024-09-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0004_restaurant_alter_favorite_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='name',
            field=models.CharField(default='NO RESTAURANT NAME GIVEN', max_length=255),
            preserve_default=False,
        ),
    ]
