# Generated by Django 5.1.1 on 2024-09-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0003_restaurant_link_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='longitude',
            new_name='lng',
        ),
    ]
