# Generated by Django 4.1 on 2024-09-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0005_restaurant_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
